import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const root = process.cwd();
const registryPath = path.join(root, 'project-status.json');
const outputPath = path.join(root, 'docs', 'PROJECT_STATUS.md');
const allowedStatuses = new Set(['pending', 'in_progress', 'blocked', 'completed']);
const validEvidenceKinds = new Set(['file', 'git_commit', 'url']);

function fail(message) {
  console.error(`Progress status check failed: ${message}`);
  process.exit(1);
}

function localPathExists(reference) {
  return fs.existsSync(path.resolve(root, reference));
}

function commitExists(reference) {
  try {
    execFileSync('git', ['cat-file', '-e', `${reference}^{commit}`], { cwd: root, stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function validate(registry) {
  if (registry.schemaVersion !== 1) fail('schemaVersion must be 1.');
  if (!registry.project?.name || !registry.project?.updatedAt) fail('project name and updatedAt are required.');
  if (!Array.isArray(registry.milestones) || registry.milestones.length === 0) fail('at least one milestone is required.');

  const ids = new Set();
  let inProgress = 0;
  for (const milestone of registry.milestones) {
    if (!milestone.id || !milestone.name || !Array.isArray(milestone.tasks)) fail('every milestone needs id, name, and tasks.');
    for (const task of milestone.tasks) {
      if (!task.id || !task.title || !task.owner || !allowedStatuses.has(task.status)) fail(`invalid task definition in ${milestone.id}.`);
      if (ids.has(task.id)) fail(`duplicate task id ${task.id}.`);
      ids.add(task.id);
      if (task.status === 'in_progress') inProgress += 1;

      if (task.status === 'completed') {
        if (!/^\d{4}-\d{2}-\d{2}$/.test(task.completedAt ?? '') || !Array.isArray(task.evidence) || task.evidence.length === 0 || task.selfCheck?.status !== 'passed' || !task.selfCheck?.method) {
          fail(`${task.id} is completed but lacks completion date, evidence, or a passed self-check.`);
        }
        for (const evidence of task.evidence) {
          if (!validEvidenceKinds.has(evidence.kind) || !evidence.ref || !evidence.note) fail(`${task.id} has invalid evidence.`);
          if (evidence.kind === 'file' && !localPathExists(evidence.ref)) fail(`${task.id} references missing evidence file ${evidence.ref}.`);
          if (evidence.kind === 'git_commit' && !commitExists(evidence.ref)) fail(`${task.id} references missing Git commit ${evidence.ref}.`);
          if (evidence.kind === 'url' && !/^https?:\/\//.test(evidence.ref)) fail(`${task.id} has an invalid evidence URL.`);
        }
      } else if (task.completedAt || task.evidence || task.selfCheck) {
        fail(`${task.id} is not completed but contains completion-only fields.`);
      }
    }
  }

  if (inProgress > 1) fail('solo workflow allows at most one in_progress task.');
  for (const milestone of registry.milestones) {
    for (const task of milestone.tasks) {
      for (const dependency of task.dependsOn ?? []) {
        if (!ids.has(dependency)) fail(`${task.id} depends on unknown task ${dependency}.`);
        const dependencyTask = registry.milestones.flatMap((item) => item.tasks).find((item) => item.id === dependency);
        if (['in_progress', 'completed'].includes(task.status) && dependencyTask.status !== 'completed') {
          fail(`${task.id} cannot be ${task.status} until dependency ${dependency} is completed.`);
        }
      }
    }
  }
}

function statusLabel(status) {
  return ({ completed: 'Completed', in_progress: 'In progress', blocked: 'Blocked', pending: 'Pending' })[status];
}

function render(registry) {
  const tasks = registry.milestones.flatMap((milestone) => milestone.tasks.map((task) => ({ ...task, milestone })));
  const complete = tasks.filter((task) => task.status === 'completed').length;
  const percentage = ((complete / tasks.length) * 100).toFixed(1);
  const active = tasks.find((task) => task.status === 'in_progress');
  const next = active ?? tasks.find((task) => task.status === 'pending' || task.status === 'blocked');
  const sourceHash = createHash('sha256').update(JSON.stringify(registry)).digest('hex').slice(0, 12);
  const lines = [
    '<!-- Generated by scripts/progress.mjs from project-status.json. Do not edit this file directly. -->',
    '# Project Status',
    '',
    `Source registry updated: ${registry.project.updatedAt}`,
    `Source hash: \`${sourceHash}\``,
    '',
    '## Progress',
    '',
    `Task-count completion: **${complete}/${tasks.length} (${percentage}%)**. This is a count of tracked tasks, not an effort estimate, product readiness claim, or market-validation result.`,
    '',
    `Current work: ${active ? `\`${active.id}\` ${active.title}` : 'No task is marked in progress.'}`,
    '',
    `Next action: ${next ? `\`${next.id}\` ${next.title}` : 'All tracked tasks are complete.'}`,
    '',
    '## Milestones',
    '',
    '| Milestone | Goal | Completed | Active |',
    '| --- | --- | ---: | ---: |'
  ];

  for (const milestone of registry.milestones) {
    const completed = milestone.tasks.filter((task) => task.status === 'completed').length;
    const activeCount = milestone.tasks.filter((task) => task.status === 'in_progress').length;
    lines.push(`| ${milestone.name} | ${milestone.goal} | ${completed}/${milestone.tasks.length} | ${activeCount} |`);
  }

  for (const milestone of registry.milestones) {
    lines.push('', `## ${milestone.name}`, '', milestone.goal, '', '| ID | Task | Owner | Status | Acceptance / self-check |', '| --- | --- | --- | --- | --- |');
    for (const task of milestone.tasks) {
      const assurance = task.status === 'completed'
        ? `Self-check passed: ${task.selfCheck.method}`
        : task.acceptance ?? 'No acceptance check recorded.';
      lines.push(`| ${task.id} | ${task.title} | ${task.owner} | ${statusLabel(task.status)} | ${assurance} |`);
    }
  }

  const completedTasks = tasks.filter((task) => task.status === 'completed').sort((a, b) => a.completedAt.localeCompare(b.completedAt) || a.id.localeCompare(b.id));
  lines.push('', '## Evidence Register', '', '| Task | Evidence type | Reference | What it verifies |', '| --- | --- | --- | --- |');
  for (const task of completedTasks) {
    for (const evidence of task.evidence) lines.push(`| ${task.id} | ${evidence.kind} | \`${evidence.ref}\` | ${evidence.note} |`);
  }
  lines.push('', '## Completion Log', '', '| Date | ID | Completed task | Evidence | Self-check |', '| --- | --- | --- | --- | --- |');
  for (const task of completedTasks) {
    const evidence = task.evidence.map((item) => `\`${item.ref}\``).join('<br>');
    lines.push(`| ${task.completedAt} | ${task.id} | ${task.title} | ${evidence} | Passed |`);
  }
  lines.push('', '## Update Protocol', '', '1. Before work, read `project-status.json` and set only one task to `in_progress`.', '2. After its acceptance check passes, add `completedAt`, concrete evidence, and a passed `selfCheck`, then set the task to `completed`.', '3. Run `node scripts/progress.mjs render`, `node scripts/progress.mjs check`, and the task-specific verification. CI rejects an invalid registry or stale generated report.', '4. Do not mark a task completed for a draft, an unverified model output, or an untested claim. Record blocked work as `blocked` with the blocker in its change record or issue.', '');
  return `${lines.join('\n').trimEnd()}\n`;
}

const mode = process.argv[2] ?? 'render';
if (!['render', 'check'].includes(mode)) fail('use either render or check.');
if (!fs.existsSync(registryPath)) fail('project-status.json is missing.');

const registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
validate(registry);
const output = render(registry);

if (mode === 'check') {
  if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, 'utf8') !== output) fail('docs/PROJECT_STATUS.md is stale; run node scripts/progress.mjs render.');
  console.log('Project status registry and generated report are valid.');
} else {
  fs.writeFileSync(outputPath, output, 'utf8');
  console.log('Generated docs/PROJECT_STATUS.md.');
}
